#!/bin/bash
# Boot screen twin of the Terminal lock design: getty-style login prompt with
# scanlines, blinking block cursor and a caps lock warning. Stages the theme
# into the directory given as $1.
set -euo pipefail
source "$(dirname "$(realpath "$0")")/../common.sh"

staging="${1:?usage: generate.sh <staging-dir>}"
mkdir -p "$staging"

bg=$(theme_color background)
fg=$(theme_color foreground)
dim=$(mix_hex "$bg" "$fg" 0.55)
family=$(mono_font_family)
host=$(hostname)
user="$USER"

bg_f=$(hex_floats "$bg"); fg_f=$(hex_floats "$fg"); dim_f=$(hex_floats "$dim")

magick -size 8x3 xc:none -fill 'rgba(0,0,0,0.12)' -draw 'rectangle 0,2 7,2' "$staging/scanline.png"
magick -size 16x32 "xc:#$fg" "$staging/cursor.png"

write_theme_ini "$staging" "$bg" "$family"
echo terminal > "$staging/design"

# Thumbnail for the explorer's boot panel.
font_file=$(fc-match -f '%{file}' "$family")
magick -size 720x405 "xc:#$bg" \
  \( -size 8x3 xc:none -fill 'rgba(0,0,0,0.12)' -draw 'rectangle 0,2 7,2' -write mpr:scan +delete -size 720x405 tile:mpr:scan \) -composite \
  -font "$font_file" -pointsize 17 -fill "#$fg" \
  -annotate +56+72 "Omarchy Linux ($host) (tty1)" \
  -annotate +56+130 "$host login: $user" \
  -annotate +56+160 "Password: " \
  -fill "#$dim" -pointsize 11 -gravity southeast -annotate +56+40 "encrypted disk  -  enter passphrase to boot" \
  "$staging/preview.png"

cat > "$staging/omarchy-boot.script" <<EOF
# Terminal lock design twin, generated by omarchy-lock-explorer.
# Colors/font/host/user were baked in from the active Omarchy theme.

bg.r = ${bg_f%%,*}; bg.g = $(echo "$bg_f" | cut -d, -f2); bg.b = $(echo "$bg_f" | cut -d, -f3);
fg.r = ${fg_f%%,*}; fg.g = $(echo "$fg_f" | cut -d, -f2); fg.b = $(echo "$fg_f" | cut -d, -f3);
dim.r = ${dim_f%%,*}; dim.g = $(echo "$dim_f" | cut -d, -f2); dim.b = $(echo "$dim_f" | cut -d, -f3);

font.main = "$family 26";
font.small = "$family 13";

Window.SetBackgroundTopColor(bg.r, bg.g, bg.b);
Window.SetBackgroundBottomColor(bg.r, bg.g, bg.b);

screen.w = Window.GetWidth();
screen.h = Window.GetHeight();

scan.image = Image("scanline.png").Tile(screen.w, screen.h);
scan.sprite = Sprite(scan.image);
scan.sprite.SetPosition(0, 0, 1);

pad = Math.Int(Math.Min(screen.w, screen.h) * 0.08);

line1.image = Image.Text("Omarchy Linux ($host) (tty1)", fg.r, fg.g, fg.b, 1, font.main);
line1.sprite = Sprite(line1.image);
line1.sprite.SetPosition(pad, pad, 10);

lh = Math.Int(line1.image.GetHeight() * 1.35);

login.image = Image.Text("$host login: $user", fg.r, fg.g, fg.b, 1, font.main);
login.sprite = Sprite(login.image);
login.sprite.SetPosition(pad, pad + lh * 2, 10);
login.sprite.SetOpacity(0);

prompt.image = Image.Text("Password: ", fg.r, fg.g, fg.b, 1, font.main);
prompt.sprite = Sprite(prompt.image);
prompt.sprite.SetPosition(pad, pad + lh * 3, 10);
prompt.sprite.SetOpacity(0);
prompt.w = prompt.image.GetWidth();

masked.sprite = Sprite();
masked.sprite.SetPosition(pad + prompt.w, pad + lh * 3, 10);
masked.sprite.SetOpacity(0);
masked.w = 0;

status.sprite = Sprite();
status.sprite.SetPosition(pad, pad + lh * 4, 10);
status.sprite.SetOpacity(0);

caps.image = Image.Text("(caps lock is on)", dim.r, dim.g, dim.b, 1, font.main);
caps.sprite = Sprite(caps.image);
caps.sprite.SetPosition(pad, pad + lh * 5, 10);
caps.sprite.SetOpacity(0);

cursor.h = line1.image.GetHeight();
cursor.w = Math.Int(cursor.h * 0.55);
cursor.image = Image("cursor.png").Scale(cursor.w, cursor.h);
cursor.sprite = Sprite(cursor.image);
cursor.sprite.SetPosition(pad + prompt.w + 2, pad + lh * 3, 11);
cursor.sprite.SetOpacity(0);

hint.image = Image.Text("encrypted disk  -  enter passphrase to boot", dim.r, dim.g, dim.b, 1, font.small);
hint.sprite = Sprite(hint.image);
hint.sprite.SetPosition(screen.w - pad - hint.image.GetWidth(), screen.h - pad - hint.image.GetHeight(), 10);
# Hidden until a passphrase prompt actually fires: plymouthd runs this theme
# for reboot/shutdown too, where "enter passphrase to boot" would mislead.
hint.sprite.SetOpacity(0);

global.password_active = 0;
global.password_shown = 0;
global.frame = 0;

fun position_cursor() {
  cursor.sprite.SetPosition(pad + prompt.w + masked.w + 2, pad + lh * 3, 11);
}

fun display_password_callback(prompt_text, bullets) {
  global.password_active = 1;
  global.password_shown = 1;

  login.sprite.SetOpacity(1);
  prompt.sprite.SetOpacity(1);
  hint.sprite.SetOpacity(1);
  status.sprite.SetOpacity(0);

  if (bullets > 32) bullets = 32;

  if (bullets > 0) {
    s = "";
    for (i = 0; i < bullets; i++) s = s + "*";
    masked.image = Image.Text(s, fg.r, fg.g, fg.b, 1, font.main);
    masked.sprite.SetImage(masked.image);
    masked.sprite.SetOpacity(1);
    masked.w = masked.image.GetWidth();
  } else {
    masked.sprite.SetOpacity(0);
    masked.w = 0;
  }

  position_cursor();
}

fun display_normal_callback() {
  global.password_active = 0;

  cursor.sprite.SetOpacity(0);
  masked.sprite.SetOpacity(0);
  prompt.sprite.SetOpacity(0);
  caps.sprite.SetOpacity(0);

  if (global.password_shown == 1) {
    status.image = Image.Text("Checking credentials...", dim.r, dim.g, dim.b, 1, font.main);
    status.sprite.SetImage(status.image);
    status.sprite.SetOpacity(1);
  }
}

fun refresh_callback() {
  global.frame++;

  if (global.password_active == 1) {
    t = global.frame % 55;
    if (t < 20) op = 1 - t / 20.0;
    else if (t < 27) op = 0;
    else if (t < 47) op = (t - 27) / 20.0;
    else op = 1;
    cursor.sprite.SetOpacity(op);

    if (Plymouth.GetCapslockState()) caps.sprite.SetOpacity(1);
    else caps.sprite.SetOpacity(0);
  }
}

message_sprite = Sprite();
message_sprite.SetPosition(pad, screen.h - pad, 10);

fun display_message_callback(text) {
  message_sprite.SetImage(Image.Text(text, dim.r, dim.g, dim.b, 1, font.small));
  message_sprite.SetOpacity(1);
}

fun hide_message_callback(text) {
  message_sprite.SetOpacity(0);
}

Plymouth.SetDisplayPasswordFunction(display_password_callback);
Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetRefreshFunction(refresh_callback);
Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);
EOF
