// Generated by Omarchy Lock Style
import QtQuick
import QtQuick.Effects
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import Quickshell.Services.Mpris
import qs.Commons
import qs.Ui

Item {
  id: root

  property string backgroundPath: ""
  property int backgroundVersion: 0
  property bool fingerprintConfigured: false
  property bool authenticatingPassword: false
  property string failureMessage: ""
  property int failedAttempts: 0
  property bool inputEnabled: true
  property bool loadBackground: true
  property string passwordText: ""
  property bool syncingPasswordText: false

  readonly property string customWallpaperPath: ""
  readonly property bool useCustomWallpaper: false
  readonly property string placeholderText: "Enter Password"
  readonly property int fieldWidth: 380
  readonly property int fieldHeight: 66
  readonly property int outlineThickness: 3
  readonly property int cornerRadius: 18
  readonly property int fieldFontSize: 22
  readonly property int passwordDotFontSize: Math.round(fieldFontSize * 1.25)
  readonly property int passwordDotLetterSpacing: Math.round(fieldFontSize * 0.18)

  readonly property real fingerprintReserve: fingerprintConfigured ? Math.round(fingerprintIcon.implicitWidth + 14) : 0
  readonly property real passwordDotScale: dotMetrics.advanceWidth > 0
    ? Math.min(1, (passwordInput.width - 4) / dotMetrics.advanceWidth)
    : 1

  readonly property bool showPasswordCursor: inputEnabled && !authenticatingPassword && failureMessage.length === 0
  readonly property bool errorState: failureMessage.length > 0
  readonly property var inputBorderSpec: errorState
    ? Border.surfaceSpec("lock", "border-error", Color.lock.borderError, root.outlineThickness, "border-alpha")
    : Border.surfaceSpec("lock", "border-active", Color.lock.borderActive, root.outlineThickness, "border-alpha")

  // Current system user info
  readonly property string currentUsername: Quickshell.env("USER") || Quickshell.env("LOGNAME") || "user"
  readonly property string userHomeDir: Quickshell.env("HOME") || ("/home/" + currentUsername)

  // Current time & date updates
  property var currentDate: new Date()
  Timer {
    interval: 1000
    running: true
    repeat: true
    onTriggered: root.currentDate = new Date()
  }

  // Developer / Motivational Quote
  readonly property var quotesList: ["May your code compile on the first try 🚀","It's not a bug, it's an undocumented feature 🐛","There is no place like 127.0.0.1 🏠","Remember to hydrate, stretch, and git commit ☕","Talk is cheap. Show me the code 💻","while (alive) { code(); drink(coffee); } ⚡","Ship it! What could possibly go wrong? 🚢","In code we trust, bugs we bust 🛡️","Keep calm and git push --force-with-lease 🔥","404: Sloth not found. Ready to build something awesome! ⚡","Clean code is the best gift to your future self ✨","sudo make it happen 🪄","Coffee: turning caffeine into clean code ☕","A commit a day keeps the merge conflicts away 🌿","May the force of zero compiler warnings be with you ⚔️","First, solve the problem. Then, write the code 🎯","The secret to great code is deleting bad code ✂️","Eat. Sleep. Code. Repeat. 🔁","Debugging: Being the detective in a movie where you are also the murderer 🕵️","There are 10 types of people: those who understand binary, and those who don't 🤖","Simplicity is the soul of efficiency 🌌","Don't comment bad code — rewrite it into poetry 📜","Deleted code is debugged code 🗑️","Hack the planet! Stay curious 󰈸","One more commit before bed... said every dev at 3 AM 🌙","Real developers test in production... just kidding 😉","Ctrl + Z is the greatest invention in human history ⏪","Never underestimate a developer with coffee and a deadline ☕","Write clean code, because the next person maintaining it might be a psychopath 📖","Everything is a file, and every day is a new commit 🐧"]
  property string activeQuote: ""
  function refreshQuote() {
    var idx = Math.floor(Math.random() * root.quotesList.length);
    activeQuote = root.quotesList[idx] || "";
  }

  signal submitPassword(string password)
  signal passwordTextEdited(string password)
  signal clearFailureRequested()
  signal wakeRequested()

  function fileUrl(path) {
    if (!path) return ""
    var encoded = String(path).split("/").map(encodeURIComponent).join("/")
    return "file://" + encoded + "?v=" + backgroundVersion
  }

  function forcePasswordFocus() {
    passwordInput.forceActiveFocus()
  }

  function clearPassword() {
    passwordTextEdited("")
  }

  function syncPasswordText() {
    if (passwordInput.text === passwordText) return
    syncingPasswordText = true
    passwordInput.text = passwordText
    syncingPasswordText = false
  }

  onPasswordTextChanged: syncPasswordText()
  onInputEnabledChanged: {
    if (inputEnabled) Qt.callLater(forcePasswordFocus)
  }

  Component.onCompleted: {
    syncPasswordText()
    refreshQuote()
    if (inputEnabled) Qt.callLater(forcePasswordFocus)
  }

  // Measures masked password advance width
  TextMetrics {
    id: dotMetrics
    font.family: Style.font.family
    font.pixelSize: root.passwordDotFontSize
    font.letterSpacing: root.passwordDotLetterSpacing
    text: "●".repeat(passwordInput.text.length)
  }

  // ==========================================
  // BACKGROUND & EFFECTS
  // ==========================================
  Rectangle {
    anchors.fill: parent
    color: Color.background

    Image {
      id: wallpaper
      anchors.fill: parent
      source: root.loadBackground ? (root.useCustomWallpaper && root.customWallpaperPath ? ("file://" + root.customWallpaperPath) : root.fileUrl(root.backgroundPath)) : ""
      fillMode: Image.PreserveAspectCrop
      asynchronous: true
      cache: false
      sourceSize.width: width
      sourceSize.height: height
    }

    MultiEffect {
      anchors.fill: wallpaper
      source: wallpaper
      autoPaddingEnabled: false
      blurEnabled: root.loadBackground && wallpaper.status === Image.Ready && true
      blur: 0.25
      blurMax: 128
      blurMultiplier: 1.25
      contrast: -0.08
    }

    // Subtle dark vignette/overlay
    Rectangle {
      anchors.fill: parent
      color: "#000000"
      opacity: 0.38
    }

    MouseArea {
      anchors.fill: parent
      hoverEnabled: true
      onClicked: { root.wakeRequested(); root.forcePasswordFocus() }
      onPositionChanged: root.wakeRequested()
    }

    // ==========================================
    // CENTER CONTENT STACK
    // ==========================================
    Column {
      id: centerColumn
      anchors.centerIn: parent
      spacing: Style.space(16)
      width: Math.max(root.fieldWidth, 480)

      
      // Clock & Date Container (Above PIN)
      Column {
        anchors.horizontalCenter: parent.horizontalCenter
        spacing: Style.space(6)
        width: parent.width

        
        
      // Clock Block
      Item {
        width: parent.width
        height: clockContent.implicitHeight
        implicitHeight: clockContent.implicitHeight
        anchors.horizontalCenter: parent.horizontalCenter

        
        Row {
          id: clockContent
          anchors.horizontalCenter: parent.horizontalCenter
          spacing: Style.space(4)

          Text {
            text: {
              var h = root.currentDate.getHours();
              if ("12h" === "12h") { h = h % 12; h = h ? h : 12; }
              return (h < 10 ? "0" : "") + h;
            }
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: 72
            font.weight: Font.Bold
            font.letterSpacing: 2
            color: Color.foreground
            verticalAlignment: Text.AlignVCenter
          }

          Text {
            text: ":"
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: 72
            font.weight: Font.Bold
            color: Color.foreground
            verticalAlignment: Text.AlignVCenter
            
            SequentialAnimation on opacity {
              loops: Animation.Infinite
              running: true
              NumberAnimation { from: 1.0; to: 0.25; duration: 900; easing.type: Easing.InOutSine }
              NumberAnimation { from: 0.25; to: 1.0; duration: 900; easing.type: Easing.InOutSine }
            }
            
          }

          Text {
            text: {
              var m = root.currentDate.getMinutes();
              return (m < 10 ? "0" : "") + m;
            }
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: 72
            font.weight: Font.Bold
            font.letterSpacing: 2
            color: Color.foreground
            verticalAlignment: Text.AlignVCenter
          }

          
          Text {
            anchors.bottom: parent.bottom
            anchors.bottomMargin: Math.round(72 * 0.16)
            text: root.currentDate.getHours() >= 12 ? "PM" : "AM"
            font.family: "JetBrainsMono Nerd Font"
            font.pixelSize: Math.round(72 * 0.28)
            font.bold: true
            color: Color.accent
            opacity: 0.9
          }
          
        }
        
      }
  
        
      // Date Block
      Text {
        width: parent.width
        anchors.horizontalCenter: parent.horizontalCenter
        text: {
          var d = root.currentDate;
          var days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
          var daysShort = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
          var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
          var monthsShort = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
          var res = "";
          if ("dddd, MMMM d" === "ddd, d MMM yyyy") {
            res = daysShort[d.getDay()] + ", " + d.getDate() + " " + monthsShort[d.getMonth()] + " " + d.getFullYear();
          } else if ("dddd, MMMM d" === "yyyy-MM-dd") {
            var mS = (d.getMonth() + 1 < 10 ? "0" : "") + (d.getMonth() + 1);
            var dS = (d.getDate() < 10 ? "0" : "") + d.getDate();
            res = d.getFullYear() + "-" + mS + "-" + dS;
          } else if ("dddd, MMMM d" === "ddd, d MMM") {
            res = daysShort[d.getDay()] + ", " + d.getDate() + " " + monthsShort[d.getMonth()];
          } else {
            res = days[d.getDay()] + ", " + months[d.getMonth()] + " " + d.getDate();
          }
          return true ? res : res.toLowerCase();
        }
        font.family: "JetBrainsMono Nerd Font"
        font.pixelSize: 16
        font.weight: Font.Medium
        color: Color.foreground
        opacity: 0.85
        horizontalAlignment: Text.AlignHCenter
      }
  
      }
      
      // User Profile & Quotes Block
      Column {
        anchors.horizontalCenter: parent.horizontalCenter
        spacing: Style.space(10)
        width: parent.width

        

        
        // Greeting Text
        Text {
          anchors.horizontalCenter: parent.horizontalCenter
          text: ("Welcome back, {user}").replace(/\{user\}/g, root.currentUsername)
          font.family: Style.font.family
          font.pixelSize: Style.font.heading
          font.bold: true
          color: Color.foreground
          horizontalAlignment: Text.AlignHCenter
        }
        

        
      }
  

      // ========================================
      // PIN / PASSWORD INPUT FIELD
      // ========================================
      BorderSurface {
        id: inputField
        width: root.fieldWidth
        height: root.fieldHeight
        anchors.horizontalCenter: parent.horizontalCenter
        color: Qt.rgba(Color.lock.background.r, Color.lock.background.g, Color.lock.background.b, 0.88)
        borderSpec: root.inputBorderSpec
        radius: root.cornerRadius
        clip: true

        
        // Breathing focus glow
        Behavior on scale { NumberAnimation { duration: 180; easing.type: Easing.OutQuad } }
        scale: passwordInput.activeFocus ? 1.015 : 1.0
        

        TextInput {
          id: passwordInput
          anchors.fill: parent
          anchors.topMargin: inputField.borderTop
          anchors.rightMargin: inputField.borderRight + 18 + root.fingerprintReserve
          anchors.bottomMargin: inputField.borderBottom
          anchors.leftMargin: inputField.borderLeft + 18 + root.fingerprintReserve
          verticalAlignment: TextInput.AlignVCenter
          horizontalAlignment: TextInput.AlignHCenter
          activeFocusOnPress: true
          clip: true
          enabled: root.inputEnabled && !root.authenticatingPassword
          readOnly: root.authenticatingPassword
          echoMode: TextInput.Password
          passwordCharacter: "●"
          passwordMaskDelay: 0
          color: Color.lock.text
          selectionColor: Color.lock.selection
          selectedTextColor: Color.lock.text
          font.family: Style.font.family
          font.pixelSize: text.length > 0 ? Math.max(1, Math.floor(root.passwordDotFontSize * root.passwordDotScale)) : root.fieldFontSize
          font.letterSpacing: text.length > 0 ? root.passwordDotLetterSpacing * root.passwordDotScale : 0
          cursorVisible: activeFocus && root.showPasswordCursor && text.length > 0
          cursorDelegate: Rectangle {
            width: 2
            color: Color.lock.text
            visible: passwordInput.cursorVisible
          }

          onTextChanged: {
            if (!root.syncingPasswordText) root.passwordTextEdited(text)
            if (text.length > 0) {
              root.wakeRequested()
            }
            if (text.length > 0 && root.failureMessage.length > 0) root.clearFailureRequested()
          }

          onAccepted: {
            var submitted = root.passwordText
            root.passwordTextEdited("")
            if (submitted.length > 0) root.submitPassword(submitted)
          }

          Keys.onPressed: function(event) {
            root.wakeRequested()
            if (event.key === Qt.Key_Escape || (event.modifiers & Qt.ControlModifier && event.key === Qt.Key_U)) {
              root.passwordTextEdited("")
              event.accepted = true
            }
          }
        }

        Text {
          anchors.fill: passwordInput
          text: root.authenticatingPassword ? "Checking…" : (root.failureMessage.length > 0 ? root.failureMessage : root.placeholderText)
          visible: passwordInput.text.length === 0
          color: root.authenticatingPassword ? Color.lock.text : (root.failureMessage.length > 0 ? Color.lock.textError : Color.lock.placeholder)
          font.family: Style.font.family
          font.pixelSize: root.fieldFontSize
          font.italic: !root.authenticatingPassword && root.failureMessage.length > 0
          horizontalAlignment: Text.AlignHCenter
          verticalAlignment: Text.AlignVCenter
          elide: Text.ElideRight
        }

        // Fingerprint indicator
        Text {
          id: fingerprintIcon
          objectName: "fingerprintIndicator"
          anchors.right: parent.right
          anchors.rightMargin: inputField.borderRight + 18
          anchors.verticalCenter: parent.verticalCenter
          visible: root.fingerprintConfigured
          text: "󰈷"
          color: Color.lock.placeholder
          font.family: Style.font.family
          font.pixelSize: Math.round(root.fieldFontSize * 1.1)
          horizontalAlignment: Text.AlignHCenter
          verticalAlignment: Text.AlignVCenter
        }
      }

      

    }

    
    // ==========================================
    // BOTTOM MEDIA WIDGET (MPRIS)
    // ==========================================
    Item {
      id: mediaWidget
      
      anchors.bottom: parent.bottom
      anchors.bottomMargin: Style.space(40)
      anchors.horizontalCenter: parent.horizontalCenter
    
      width: mediaCard.width
      height: mediaCard.height

      readonly property var players: Mpris.players ? Mpris.players.values : []
      readonly property var activePlayer: {
        for (var i = 0; i < players.length; i++) {
          if (players[i] && (players[i].isPlaying || (players[i].trackTitle && players[i].trackTitle.length > 0))) {
            return players[i];
          }
        }
        return null;
      }
      readonly property bool hasTrack: activePlayer !== null && !root.authenticatingPassword && !!(activePlayer.trackTitle || activePlayer.trackArtist)
      readonly property string trackLabel: {
        if (!activePlayer) return "";
        var title = activePlayer.trackTitle || "Unknown Track";
        var artist = activePlayer.trackArtist || "";
        return artist ? (title + " — " + artist) : title;
      }

      visible: hasTrack

      BorderSurface {
        id: mediaCard
        width: Math.min(mediaRow.implicitWidth + Style.space(28), Style.space(460))
        height: Style.space(36)
        radius: Style.cornerRadius
        color: Qt.rgba(Color.background.r, Color.background.g, Color.background.b, 0.82)
        borderSpec: Border.controlSpec("normal", Color.foreground, Color.accent)
        clip: true

        Row {
          id: mediaRow
          anchors.centerIn: parent
          spacing: Style.space(8)

          Text {
            text: "󰎈"
            color: Color.accent
            font.family: Style.font.family
            font.pixelSize: Style.space(16)
            anchors.verticalCenter: parent.verticalCenter
          }

          Text {
            text: mediaWidget.trackLabel
            color: Color.foreground
            font.family: Style.font.family
            font.pixelSize: Style.font.body
            font.bold: true
            anchors.verticalCenter: parent.verticalCenter
            elide: Text.ElideRight
            width: Math.min(implicitWidth, Style.space(380))
          }
        }
      }
    }
  

  }
}
