#!/usr/bin/env python3
"""Rasterise country borders into the dot grid WorldMap.qml draws.

    curl -sSo /tmp/world.geojson \
      https://raw.githubusercontent.com/holtzy/D3-graph-gallery/master/DATA/world.geojson
    tools/rasterize-map.py /tmp/world.geojson > MapData.js

The GeoJSON is only a build input: the generated MapData.js is what ships, so a
clone of this repository never needs network access or this script.

Grid and bounds have to stay in sync with Model.projectToMap(), which places the
marker on the same projection. LAT_TOP/LAT_BOTTOM crop Antarctica and the high
Arctic, the way dot-matrix world maps normally do.

WIDTH is chosen for the panel it renders in: at 330px, 72 columns give ~4.6px per
cell. Going wider (the IVPN plugin this is modelled on uses 96) turns the dots
into a smear at this width.
"""

import json
import sys

WIDTH, HEIGHT = 72, 30
LAT_TOP, LAT_BOTTOM = 82.0, -56.0

# Fraction of a cell that must be land for the dot to be drawn. Too low and the
# Mediterranean fills in; too high and coastlines and islands disappear.
COVERAGE = 0.38


def load_polygons(path):
    """Flatten every Polygon/MultiPolygon into (bbox, rings) pairs."""
    data = json.load(open(path))
    polygons = []
    for feature in data["features"]:
        geometry = feature.get("geometry") or {}
        kind, coords = geometry.get("type"), geometry.get("coordinates")
        if not coords:
            continue
        groups = [coords] if kind == "Polygon" else coords if kind == "MultiPolygon" else []
        for polygon in groups:
            rings = [[(float(p[0]), float(p[1])) for p in ring] for ring in polygon]
            xs = [p[0] for p in rings[0]]
            ys = [p[1] for p in rings[0]]
            polygons.append(((min(xs), min(ys), max(xs), max(ys)), rings))
    return polygons


def spans_at(lat, polygons):
    """Longitude intervals covered by land at one latitude.

    Scanline rather than per-cell point-in-polygon: every edge is visited once
    per latitude instead of once per cell, which is what makes supersampling
    affordable. Each polygon is resolved on its own with the even-odd rule, so
    its holes subtract correctly without neighbouring countries cancelling each
    other along a shared border.
    """
    spans = []
    for (min_x, min_y, max_x, max_y), rings in polygons:
        if not (min_y <= lat <= max_y):
            continue
        crossings = []
        for ring in rings:
            count = len(ring)
            for i in range(count):
                x1, y1 = ring[i]
                x2, y2 = ring[(i + 1) % count]
                if (y1 > lat) != (y2 > lat):
                    crossings.append((x2 - x1) * (lat - y1) / (y2 - y1) + x1)
        crossings.sort()
        for i in range(0, len(crossings) - 1, 2):
            spans.append((crossings[i], crossings[i + 1]))
    return spans


def merge(spans):
    """Union of overlapping intervals, so shared coastline is not counted twice."""
    if not spans:
        return []
    ordered = sorted(spans)
    merged = [list(ordered[0])]
    for start, end in ordered[1:]:
        if start <= merged[-1][1]:
            merged[-1][1] = max(merged[-1][1], end)
        else:
            merged.append([start, end])
    return merged


def overlap(spans, left, right):
    """How much of [left, right] the spans cover."""
    total = 0.0
    for start, end in spans:
        low, high = max(start, left), min(end, right)
        if high > low:
            total += high - low
    return total


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: rasterize-map.py <world.geojson>")

    polygons = load_polygons(sys.argv[1])

    # Three scanlines per row, and a cell is land when enough of its width is
    # covered — not merely when a span touches it. Centre sampling alone drops
    # coastlines (Stockholm landed in the Baltic); any-overlap floods enclosed
    # seas until Eurasia is one blob.
    rows = []
    for row in range(HEIGHT):
        top = LAT_TOP - row * (LAT_TOP - LAT_BOTTOM) / HEIGHT
        bottom = LAT_TOP - (row + 1) * (LAT_TOP - LAT_BOTTOM) / HEIGHT
        samples = [merge(spans_at(top + (bottom - top) * step, polygons))
                   for step in (0.15, 0.5, 0.85)]

        cell_width = 360.0 / WIDTH
        cells = []
        for col in range(WIDTH):
            left = -180.0 + col * cell_width
            right = left + cell_width
            covered = sum(overlap(spans, left, right) for spans in samples)
            cells.append("1" if covered / (len(samples) * cell_width) >= COVERAGE else "0")
        rows.append("".join(cells))

    out = sys.stdout
    out.write("// Generated by tools/rasterize-map.py — do not edit by hand.\n")
    out.write("//\n")
    out.write("// One character per grid cell: 1 is land, 0 is water. The projection that\n")
    out.write("// places the marker on this grid lives in Model.projectToMap(), and the\n")
    out.write("// bounds below have to match it.\n\n")
    out.write(".pragma library\n\n")
    out.write("var WIDTH = %d\n" % WIDTH)
    out.write("var HEIGHT = %d\n" % HEIGHT)
    out.write("var LAT_TOP = %s\n" % LAT_TOP)
    out.write("var LAT_BOTTOM = %s\n\n" % LAT_BOTTOM)
    out.write("var rows = [\n")
    out.write(",\n".join('  "%s"' % r for r in rows))
    out.write("\n]\n")


if __name__ == "__main__":
    main()
