#!/usr/bin/env bash
# ==============================================================================
# voyager-config: config deployment stage
# Omarchy hosts  -> canonical tree under configs/
# other hosts     -> portable tree under configs/portable/ + generated themes
# Every overwrite is backed up to ~/.voyager-config-backup/<ts>/
# ==============================================================================
set -Eeuo pipefail

VOYAGER_ROOT="${VOYAGER_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
export VOYAGER_ROOT
# shellcheck source=lib/common.sh
source "$VOYAGER_ROOT/lib/common.sh"
# shellcheck source=lib/distro.sh
source "$VOYAGER_ROOT/lib/distro.sh"
detect_distro

CFGS="$VOYAGER_CONFIGS"
PORT="$CFGS/portable"
HOME_CFG="$HOME/.config"
BIN_DST="$HOME/.local/bin"
SKILL_DST="$HOME/.agents/skills"
WALL_DST="$HOME_CFG/wallpapers"

deploy_bin_skills_shared() {
	deploy_tree "$CFGS/bin" "$BIN_DST" --exec
	deploy_tree "$CFGS/opencode" "$HOME_CFG/opencode" node_modules
	deploy_tree "$CFGS/agents/skills" "$SKILL_DST"
	deploy_files "$CFGS/environment.d" "$HOME_CFG/environment.d"
	deploy_files "$CFGS/browser-flags" "$HOME_CFG"
	deploy_tree "$CFGS/wallpapers" "$WALL_DST"
	# Antigravity settings (gemini CLI)
	mkdir -p "$HOME/.gemini/antigravity-cli"
	deploy_file "$CFGS/antigravity/settings.json" "$HOME/.gemini/antigravity-cli/settings.json"
	# Desktop entries carried in the repo (battlenet generated by gaming stage)
	if [[ -d "$CFGS/../apps" ]]; then
		mkdir -p "$HOME/.local/share/applications"
		for f in "$VOYAGER_ROOT/apps/"*.desktop; do
			[[ -e "$f" ]] || continue
			name="$(basename "$f")"
			[[ "$name" == "battlenet.desktop" ]] && continue # generated by gaming stage
			[[ -f "$HOME/.local/share/applications/$name" ]] || deploy_file "$f" "$HOME/.local/share/applications/$name"
		done
	fi
}

deploy_shell_common() {
	# shared shell functions/aliases (identical across canons)
	mkdir -p "$HOME_CFG/shell/fns"
	deploy_files "$CFGS/shell/fns" "$HOME_CFG/shell/fns"
	deploy_file "$CFGS/shell/aliases" "$HOME_CFG/shell/aliases"
}

deploy_common_apps() {
	# apps with kindred configuration everywhere
	deploy_tree "$CFGS/btop" "$HOME_CFG/btop"
	deploy_files "$CFGS/lazygit" "$HOME_CFG/lazygit"
	deploy_file "$CFGS/starship.toml" "$HOME_CFG/starship.toml"
}

deploy_omarchy_tail() {
	deploy_tree "$CFGS/omarchy" "$HOME_CFG/omarchy" __pycache__ lock-videos
	deploy_tree "$CFGS/hypr" "$HOME_CFG/hypr"
	deploy_file "$CFGS/fastfetch/config.jsonc" "$HOME_CFG/fastfetch/config.jsonc"
	deploy_file "$CFGS/mise/config.toml" "$HOME_CFG/mise/config.toml"
	# Terminal configs (machine-canonical fonts)
	mkdir -p "$HOME_CFG/foot" "$HOME_CFG/alacritty" "$HOME_CFG/tmux"
	[[ -f "$CFGS/foot/foot.ini" ]] && deploy_file "$CFGS/foot/foot.ini" "$HOME_CFG/foot/foot.ini" || true
	[[ -f "$CFGS/alacritty/alacritty.toml" ]] && deploy_file "$CFGS/alacritty/alacritty.toml" "$HOME_CFG/alacritty/alacritty.toml" || true
	[[ -f "$CFGS/tmux/tmux.conf" ]] && deploy_file "$CFGS/tmux/tmux.conf" "$HOME_CFG/tmux/tmux.conf" || true
	deploy_file "$CFGS/git/config" "$HOME_CFG/git/config"
	if command -v docker >/dev/null 2>&1; then
		mkdir -p "$HOME_CFG/docker"
		[[ -f "$CFGS/docker/daemon.json" ]] && deploy_file "$CFGS/docker/daemon.json" "$HOME_CFG/docker/daemon.json" || true
	fi
	# .bashrc — respect an omarchy-managed file (env-bootstrap), else deploy ours
	if [[ -f "$HOME/.bashrc" ]] && grep -q "omarchy/default/bash/env-bootstrap" "$HOME/.bashrc" 2>/dev/null; then
		log "\\\$HOME/.bashrc is managed by omarchy; leaving it untouched."
	else
		deploy_file "$CFGS/shell/.bashrc" "$HOME/.bashrc"
	fi
}

deploy_portable_tail() {
	deploy_tree "$PORT/alacritty" "$HOME_CFG/alacritty"
	deploy_tree "$PORT/foot" "$HOME_CFG/foot"
	deploy_tree "$PORT/tmux" "$HOME_CFG/tmux"
	deploy_tree "$PORT/btop" "$HOME_CFG/btop"
	deploy_file "$PORT/starship/starship.toml" "$HOME_CFG/starship.toml"
	deploy_file "$PORT/fastfetch/config.jsonc" "$HOME_CFG/fastfetch/config.jsonc"
	deploy_file "$PORT/git/config" "$HOME_CFG/git/config"
	deploy_file "$PORT/mise/config.toml" "$HOME_CFG/mise/config.toml"
	deploy_file "$PORT/shell/.bashrc" "$HOME/.bashrc"
	deploy_file "$PORT/omarchy/shell.json.reference" "$HOME_CFG/omarchy/shell.json.reference"
	deploy_files "$PORT/lazygit" "$HOME_CFG/lazygit"
	if command -v docker >/dev/null 2>&1; then
		mkdir -p "$HOME_CFG/docker"
		deploy_file "$PORT/docker/daemon.json" "$HOME_CFG/docker/daemon.json"
	fi
	# Generate platform theme assets
	bash "$VOYAGER_SCRIPTS/theme/gen-hyprland.sh" "$VOYAGER_THEMES/aether" "$HOME_CFG/hypr"
	bash "$VOYAGER_SCRIPTS/theme/gen-rofi.sh" "$VOYAGER_THEMES/aether" "$HOME_CFG/rofi"
	bash "$VOYAGER_SCRIPTS/theme/gen-shell-bar.sh" "$VOYAGER_THEMES/aether" "$HOME_CFG/quickshell"
}

main() {
	deploy_bin_skills_shared
	if ((IS_OMARCHY)); then
		deploy_omarchy_tail
		deploy_common_apps
		deploy_shell_common
	else
		deploy_portable_tail
		deploy_shell_common
	fi
	ok "configs stage complete (omarchy=$IS_OMARCHY)."
}

main "$@"
