#!/usr/bin/env bash
#
# Generate a standalone hyprland.conf from an Omarchy theme dir + keybindings.
# Works with standard Hyprland across distributions without Omarchy Lua runtime.
#
set -Eeuo pipefail

THEME_DIR="${1:?usage: gen-hyprland.sh <theme-dir>}"
OUT_DIR="${2:-"$HOME/.config/hypr"}"
mkdir -p "$OUT_DIR"

# --- Parse colors from colors.toml ---------------------------------------
accent="$(grep '^accent' "$THEME_DIR/colors.toml"        | head -1 | sed -E 's/.*#([0-9a-fA-F]{6}).*/\1/' || true)"
background="$(grep '^background' "$THEME_DIR/colors.toml" | head -1 | sed -E 's/.*#([0-9a-fA-F]{6}).*/\1/' || true)"
foreground="$(grep '^foreground' "$THEME_DIR/colors.toml" | head -1 | sed -E 's/.*#([0-9a-fA-F]{6}).*/\1/' || true)"

accent="${accent:-78824b}"
background="${background:-222222}"
foreground="${foreground:-c2c2b0}"

# Hyprland color syntax requires rgb(...) or rgba(...)
active_border="rgb($accent)"
inactive_border="rgba(595959aa)"

cat > "$OUT_DIR/hyprland.conf" <<EOF
# Generated by Landfall from $THEME_DIR/colors.toml
# Standalone Hyprland configuration (Aether palette)

# --- Monitor --------------------------------------------------------------
monitor=,preferred,auto,1

# --- Startup Daemons ------------------------------------------------------
exec-once = foot --server
exec-once = sh -c 'if command -v quickshell &>/dev/null; then quickshell -p ~/.config/quickshell; elif command -v qs &>/dev/null; then qs -p ~/.config/quickshell; else waybar; fi'
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = sh -c 'swaybg -i ~/.config/wallpapers/aether-dark-4k.jpg -m fill 2>/dev/null || true'

# --- General --------------------------------------------------------------
general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10
    col.active_border = $active_border
    col.inactive_border = $inactive_border
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}


cursor {
    inactive_timeout = 5
}

decoration {
    rounding = 8
    blur {
        enabled = true
        size = 3
        passes = 2
    }
    shadow {
        enabled = true
        range = 20
    }
}

animations {
    enabled = true
    bezier = easeOutQuint,0.23,1,0.32,1
    animation = windows,1,5,easeOutQuint
    animation = windowsOut,1,4,easeOutQuint
    animation = fade,1,5,easeOutQuint
    animation = workspaces,1,4,easeOutQuint
}

input {
    kb_layout = us
    follow_mouse = 1
    numlock_by_default = true
}

# --- Keybindings ----------------------------------------------------------
\$mainMod = SUPER

# App & Menu Launchers
bind = \$mainMod, SPACE, exec, sh -c 'rofi -show drun || wofi --show drun'
bind = \$mainMod, RETURN, exec, foot

# Clipboard History Picker
bind = \$mainMod SHIFT, V, exec, sh -c 'cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy'

# TUI Dashboards
bind = \$mainMod SHIFT, G, exec, foot -e lazygit
bind = \$mainMod SHIFT, D, exec, foot -e lazydocker
bind = \$mainMod SHIFT, B, exec, foot -e btop

# AI Coding Agent (OpenCode / Antigravity / Claude launched in terminal)
bind = \$mainMod, A, exec, foot -e ~/.local/bin/omarchy-agent

# Password Manager (Bitwarden)
bind = \$mainMod CTRL, SLASH, exec, foot -e bw unlock

# File Manager
bind = \$mainMod SHIFT, F, exec, thunar

# Workspaces (1-9)
bind = \$mainMod, 1, workspace, 1
bind = \$mainMod, 2, workspace, 2
bind = \$mainMod, 3, workspace, 3
bind = \$mainMod, 4, workspace, 4
bind = \$mainMod, 5, workspace, 5
bind = \$mainMod, 6, workspace, 6
bind = \$mainMod, 7, workspace, 7
bind = \$mainMod, 8, workspace, 8
bind = \$mainMod, 9, workspace, 9

bind = \$mainMod SHIFT, 1, movetoworkspace, 1
bind = \$mainMod SHIFT, 2, movetoworkspace, 2
bind = \$mainMod SHIFT, 3, movetoworkspace, 3
bind = \$mainMod SHIFT, 4, movetoworkspace, 4
bind = \$mainMod SHIFT, 5, movetoworkspace, 5
bind = \$mainMod SHIFT, 6, movetoworkspace, 6
bind = \$mainMod SHIFT, 7, movetoworkspace, 7
bind = \$mainMod SHIFT, 8, movetoworkspace, 8
bind = \$mainMod SHIFT, 9, movetoworkspace, 9

# Window Management
bind = \$mainMod, Q, killactive
bind = \$mainMod, F, fullscreen
bind = \$mainMod, V, togglefloating
bind = \$mainMod, J, togglesplit
bind = \$mainMod, W, exec, sh -c 'rofi -show window || wofi --show run'

# Focus Navigation
bind = \$mainMod, H, movefocus, l
bind = \$mainMod, L, movefocus, r
bind = \$mainMod, K, movefocus, u
bind = \$mainMod, J, movefocus, d
bind = \$mainMod SHIFT, H, movewindow, l
bind = \$mainMod SHIFT, L, movewindow, r
bind = \$mainMod SHIFT, K, movewindow, u
bind = \$mainMod SHIFT, J, movewindow, d

# Screenshots (grim + slurp)
bind = \$mainMod SHIFT, S, exec, sh -c 'grim -g "\$(slurp)" - | wl-copy'
bind = , Print, exec, sh -c 'grim - | wl-copy'

# --- Environment ----------------------------------------------------------
env = XCURSOR_THEME,capitaine-cursors
env = GDK_SCALE,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
EOF

echo "Wrote $OUT_DIR/hyprland.conf"
