#!/usr/bin/env bash
set -euo pipefail

# Generate NixOS skill reference files from official documentation repositories
#
# Sources:
#   1. NixOS/nix.dev        - tutorials, guides, concepts, glossary
#   2. NixOS/nixpkgs        - NixOS manual (nixos/doc/manual/)
#   3. NixOS/nix-pills      - progressive Nix learning series
#   4. NixOS/release-wiki   - NixOS release process (mdBook)
#
# Usage: ./scripts/generate-references.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REFS_DIR="$SKILL_DIR/references"
WORK_DIR=$(mktemp -d)

NIXDEV_REPO="https://github.com/NixOS/nix.dev.git"
NIXPKGS_REPO="https://github.com/NixOS/nixpkgs.git"
PILLS_REPO="https://github.com/NixOS/nix-pills.git"
RELEASE_REPO="https://github.com/NixOS/release-wiki.git"

cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

# ── Clone all sources ──────────────────────────────────────────────────

echo "==> Cloning source repositories (parallel)..."

git clone --depth 1 --quiet "$NIXDEV_REPO" "$WORK_DIR/nix.dev" &
PID_NIXDEV=$!

git clone --depth 1 --quiet "$PILLS_REPO" "$WORK_DIR/nix-pills" &
PID_PILLS=$!

git clone --depth 1 --quiet "$RELEASE_REPO" "$WORK_DIR/release-wiki" &
PID_RELEASE=$!

# Sparse checkout for nixpkgs (only nixos/doc/manual/)
(
    git clone --depth 1 --filter=blob:none --sparse --quiet "$NIXPKGS_REPO" "$WORK_DIR/nixpkgs"
    git -C "$WORK_DIR/nixpkgs" sparse-checkout set nixos/doc/manual/
) &
PID_NIXPKGS=$!

wait $PID_NIXDEV $PID_PILLS $PID_RELEASE $PID_NIXPKGS
echo "    All repos cloned."

# ── Collect version info ───────────────────────────────────────────────

NIXDEV_COMMIT=$(git -C "$WORK_DIR/nix.dev" rev-parse --short HEAD)
NIXDEV_DATE=$(git -C "$WORK_DIR/nix.dev" log -1 --format=%ci)
NIXPKGS_COMMIT=$(git -C "$WORK_DIR/nixpkgs" rev-parse --short HEAD)
NIXPKGS_DATE=$(git -C "$WORK_DIR/nixpkgs" log -1 --format=%ci)
PILLS_COMMIT=$(git -C "$WORK_DIR/nix-pills" rev-parse --short HEAD)
PILLS_DATE=$(git -C "$WORK_DIR/nix-pills" log -1 --format=%ci)
RELEASE_COMMIT=$(git -C "$WORK_DIR/release-wiki" rev-parse --short HEAD)
RELEASE_DATE=$(git -C "$WORK_DIR/release-wiki" log -1 --format=%ci)

echo "==> Source versions:"
echo "    nix.dev:      $NIXDEV_COMMIT ($NIXDEV_DATE)"
echo "    nixpkgs:      $NIXPKGS_COMMIT ($NIXPKGS_DATE)"
echo "    nix-pills:    $PILLS_COMMIT ($PILLS_DATE)"
echo "    release-wiki: $RELEASE_COMMIT ($RELEASE_DATE)"

# Shorthand paths
NIXDEV="$WORK_DIR/nix.dev/source"
MANUAL="$WORK_DIR/nixpkgs/nixos/doc/manual"
PILLS="$WORK_DIR/nix-pills/pills"
RELEASE="$WORK_DIR/release-wiki/src"

mkdir -p "$REFS_DIR"

# ── Helpers ────────────────────────────────────────────────────────────

MISSING_SOURCES=0

# copy_page <source_file> <output_filename> <source_url> <repo_label>
copy_page() {
    local src="$1" dst="$REFS_DIR/$2" url="$3" repo="$4"
    if [[ ! -f "$src" ]]; then
        echo "  WARN: $(basename "$src") not found, skipping"
        MISSING_SOURCES=$((MISSING_SOURCES + 1))
        return
    fi
    {
        echo "<!-- source: $url -->"
        echo "<!-- repo: $repo -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        cat "$src"
    } > "$dst"
    echo "  OK: $2"
}

# merge_pages <output_filename> <header> <source_url> <repo_label> <file1> [file2...]
merge_pages() {
    local name="$1" dst="$REFS_DIR/$1" header="$2" url="$3" repo="$4"
    shift 4
    {
        echo "<!-- source: $url -->"
        echo "<!-- repo: $repo -->"
        echo "<!-- auto-generated by scripts/generate-references.sh - DO NOT EDIT MANUALLY -->"
        echo ""
        echo "# $header"
        echo ""
        for src in "$@"; do
            if [[ -f "$src" ]]; then
                cat "$src"
                echo ""
                echo "---"
                echo ""
            else
                echo "  WARN: $(basename "$src") not found, skipping from merge" >&2
                MISSING_SOURCES=$((MISSING_SOURCES + 1))
            fi
        done
    } > "$dst"
    echo "  OK: $name (merged)"
}

echo ""
echo "==> Generating reference files..."

# ── nix.dev: Tutorials & Guides ───────────────────────────────────────

echo ""
echo "--- nix.dev ---"

copy_page "$NIXDEV/install-nix.md" \
    "install-nix.md" \
    "https://nix.dev/install-nix" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nix-language.md" \
    "nix-language.md" \
    "https://nix.dev/tutorials/nix-language" "NixOS/nix.dev"

merge_pages "first-steps.md" "First Steps with Nix" \
    "https://nix.dev/tutorials/first-steps" "NixOS/nix.dev" \
    "$NIXDEV/tutorials/first-steps/ad-hoc-shell-environments.md" \
    "$NIXDEV/tutorials/first-steps/declarative-shell.md" \
    "$NIXDEV/tutorials/first-steps/reproducible-scripts.md" \
    "$NIXDEV/tutorials/first-steps/towards-reproducibility-pinning-nixpkgs.md"

copy_page "$NIXDEV/tutorials/packaging-existing-software.md" \
    "packaging-tutorial.md" \
    "https://nix.dev/tutorials/packaging-existing-software" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/callpackage.md" \
    "callpackage.md" \
    "https://nix.dev/tutorials/callpackage" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/cross-compilation.md" \
    "cross-compilation.md" \
    "https://nix.dev/tutorials/cross-compilation" "NixOS/nix.dev"

merge_pages "module-system.md" "Nix Module System" \
    "https://nix.dev/tutorials/module-system" "NixOS/nix.dev" \
    "$NIXDEV/tutorials/module-system/a-basic-module/index.md" \
    "$NIXDEV/tutorials/module-system/deep-dive.md"

copy_page "$NIXDEV/tutorials/working-with-local-files.md" \
    "working-with-local-files.md" \
    "https://nix.dev/tutorials/working-with-local-files" "NixOS/nix.dev"

copy_page "$NIXDEV/concepts/flakes.md" \
    "flakes.md" \
    "https://nix.dev/concepts/flakes" "NixOS/nix.dev"

merge_pages "faq.md" "NixOS / Nix FAQ" \
    "https://nix.dev/concepts/faq" "NixOS/nix.dev" \
    "$NIXDEV/concepts/faq.md" \
    "$NIXDEV/guides/faq.md"

copy_page "$NIXDEV/guides/best-practices.md" \
    "best-practices.md" \
    "https://nix.dev/guides/best-practices" "NixOS/nix.dev"

copy_page "$NIXDEV/guides/troubleshooting.md" \
    "troubleshooting.md" \
    "https://nix.dev/guides/troubleshooting" "NixOS/nix.dev"

copy_page "$NIXDEV/reference/glossary.md" \
    "glossary.md" \
    "https://nix.dev/reference/glossary" "NixOS/nix.dev"

copy_page "$NIXDEV/reference/pinning-nixpkgs.md" \
    "pinning-nixpkgs.md" \
    "https://nix.dev/reference/pinning-nixpkgs" "NixOS/nix.dev"

merge_pages "recipes.md" "Nix Recipes & How-To Guides" \
    "https://nix.dev/guides/recipes" "NixOS/nix.dev" \
    "$NIXDEV/guides/recipes/direnv.md" \
    "$NIXDEV/guides/recipes/continuous-integration-github-actions.md" \
    "$NIXDEV/guides/recipes/dependency-management.md" \
    "$NIXDEV/guides/recipes/python-environment.md" \
    "$NIXDEV/guides/recipes/add-binary-cache.md" \
    "$NIXDEV/guides/recipes/sharing-dependencies.md" \
    "$NIXDEV/guides/recipes/post-build-hook.md"

# nix.dev NixOS-specific tutorials
copy_page "$NIXDEV/tutorials/nixos/nixos-configuration-on-vm.md" \
    "nixos-vm-tutorial.md" \
    "https://nix.dev/tutorials/nixos/nixos-configuration-on-vm" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/building-and-running-docker-images.md" \
    "nixos-docker-tutorial.md" \
    "https://nix.dev/tutorials/nixos/building-and-running-docker-images" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/building-bootable-iso-image.md" \
    "nixos-iso-tutorial.md" \
    "https://nix.dev/tutorials/nixos/building-bootable-iso-image" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/integration-testing-using-virtual-machines.md" \
    "nixos-testing-tutorial.md" \
    "https://nix.dev/tutorials/nixos/integration-testing-using-virtual-machines" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/deploying-nixos-using-terraform.md" \
    "nixos-terraform-tutorial.md" \
    "https://nix.dev/tutorials/nixos/deploying-nixos-using-terraform" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/distributed-builds-setup.md" \
    "nixos-distributed-builds.md" \
    "https://nix.dev/tutorials/nixos/distributed-builds-setup" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/installing-nixos-on-a-raspberry-pi.md" \
    "nixos-raspberry-pi.md" \
    "https://nix.dev/tutorials/nixos/installing-nixos-on-a-raspberry-pi" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/provisioning-remote-machines.md" \
    "nixos-remote-machines.md" \
    "https://nix.dev/tutorials/nixos/provisioning-remote-machines" "NixOS/nix.dev"

copy_page "$NIXDEV/tutorials/nixos/binary-cache-setup.md" \
    "nixos-binary-cache.md" \
    "https://nix.dev/tutorials/nixos/binary-cache-setup" "NixOS/nix.dev"

# ── nixpkgs: NixOS Manual ─────────────────────────────────────────────

echo ""
echo "--- nixpkgs NixOS Manual ---"

merge_pages "nixos-installation.md" "NixOS Installation" \
    "https://nixos.org/manual/nixos/stable/#ch-installation" "NixOS/nixpkgs" \
    "$MANUAL/installation/obtaining.chapter.md" \
    "$MANUAL/installation/installing.chapter.md" \
    "$MANUAL/installation/installing-usb.section.md" \
    "$MANUAL/installation/installing-pxe.section.md" \
    "$MANUAL/installation/installing-kexec.section.md" \
    "$MANUAL/installation/installing-virtualbox-guest.section.md" \
    "$MANUAL/installation/installing-behind-a-proxy.section.md" \
    "$MANUAL/installation/installing-from-other-distro.section.md"

copy_page "$MANUAL/installation/upgrading.chapter.md" \
    "nixos-upgrading.md" \
    "https://nixos.org/manual/nixos/stable/#sec-upgrading" "NixOS/nixpkgs"

copy_page "$MANUAL/installation/changing-config.chapter.md" \
    "nixos-changing-config.md" \
    "https://nixos.org/manual/nixos/stable/#sec-changing-config" "NixOS/nixpkgs"

merge_pages "nixos-config-syntax.md" "NixOS Configuration Syntax" \
    "https://nixos.org/manual/nixos/stable/#sec-configuration-syntax" "NixOS/nixpkgs" \
    "$MANUAL/configuration/config-syntax.chapter.md" \
    "$MANUAL/configuration/config-file.section.md" \
    "$MANUAL/configuration/abstractions.section.md" \
    "$MANUAL/configuration/modularity.section.md"

merge_pages "nixos-package-mgmt.md" "NixOS Package Management" \
    "https://nixos.org/manual/nixos/stable/#sec-package-management" "NixOS/nixpkgs" \
    "$MANUAL/configuration/package-mgmt.chapter.md" \
    "$MANUAL/configuration/declarative-packages.section.md" \
    "$MANUAL/configuration/ad-hoc-packages.section.md" \
    "$MANUAL/configuration/adding-custom-packages.section.md" \
    "$MANUAL/configuration/customizing-packages.section.md"

copy_page "$MANUAL/configuration/user-mgmt.chapter.md" \
    "nixos-user-mgmt.md" \
    "https://nixos.org/manual/nixos/stable/#sec-user-management" "NixOS/nixpkgs"

merge_pages "nixos-networking.md" "NixOS Networking" \
    "https://nixos.org/manual/nixos/stable/#sec-networking" "NixOS/nixpkgs" \
    "$MANUAL/configuration/networking.chapter.md" \
    "$MANUAL/configuration/network-manager.section.md" \
    "$MANUAL/configuration/ssh.section.md" \
    "$MANUAL/configuration/ipv4-config.section.md" \
    "$MANUAL/configuration/ipv6-config.section.md" \
    "$MANUAL/configuration/firewall.section.md" \
    "$MANUAL/configuration/wireless.section.md" \
    "$MANUAL/configuration/ad-hoc-network-config.section.md" \
    "$MANUAL/configuration/renaming-interfaces.section.md"

merge_pages "nixos-filesystems.md" "NixOS Filesystems" \
    "https://nixos.org/manual/nixos/stable/#ch-file-systems" "NixOS/nixpkgs" \
    "$MANUAL/configuration/file-systems.chapter.md" \
    "$MANUAL/configuration/luks-file-systems.section.md" \
    "$MANUAL/configuration/sshfs-file-systems.section.md" \
    "$MANUAL/configuration/overlayfs.section.md"

merge_pages "nixos-display-server.md" "NixOS Display Server (X11 / Wayland)" \
    "https://nixos.org/manual/nixos/stable/#sec-x11" "NixOS/nixpkgs" \
    "$MANUAL/configuration/x-windows.chapter.md" \
    "$MANUAL/configuration/wayland.chapter.md" \
    "$MANUAL/configuration/xfce.chapter.md" \
    "$MANUAL/configuration/gpu-accel.chapter.md"

copy_page "$MANUAL/configuration/linux-kernel.chapter.md" \
    "nixos-linux-kernel.md" \
    "https://nixos.org/manual/nixos/stable/#sec-kernel-config" "NixOS/nixpkgs"

merge_pages "nixos-containers.md" "NixOS Containers" \
    "https://nixos.org/manual/nixos/stable/#ch-containers" "NixOS/nixpkgs" \
    "$MANUAL/administration/containers.chapter.md" \
    "$MANUAL/administration/declarative-containers.section.md" \
    "$MANUAL/administration/imperative-containers.section.md" \
    "$MANUAL/administration/container-networking.section.md"

copy_page "$MANUAL/configuration/kubernetes.chapter.md" \
    "nixos-kubernetes.md" \
    "https://nixos.org/manual/nixos/stable/#sec-kubernetes" "NixOS/nixpkgs"

merge_pages "nixos-administration.md" "NixOS Administration" \
    "https://nixos.org/manual/nixos/stable/#ch-running" "NixOS/nixpkgs" \
    "$MANUAL/administration/service-mgmt.chapter.md" \
    "$MANUAL/administration/logging.chapter.md" \
    "$MANUAL/administration/rebooting.chapter.md" \
    "$MANUAL/administration/rollback.section.md" \
    "$MANUAL/administration/maintenance-mode.section.md" \
    "$MANUAL/administration/user-sessions.chapter.md" \
    "$MANUAL/administration/control-groups.chapter.md" \
    "$MANUAL/administration/cleaning-store.chapter.md" \
    "$MANUAL/administration/troubleshooting.chapter.md" \
    "$MANUAL/administration/boot-problems.section.md" \
    "$MANUAL/administration/network-problems.section.md" \
    "$MANUAL/administration/store-corruption.section.md"

merge_pages "nixos-writing-modules.md" "Writing NixOS Modules" \
    "https://nixos.org/manual/nixos/stable/#sec-writing-modules" "NixOS/nixpkgs" \
    "$MANUAL/development/writing-modules.chapter.md" \
    "$MANUAL/development/option-declarations.section.md" \
    "$MANUAL/development/option-def.section.md" \
    "$MANUAL/development/option-types.section.md" \
    "$MANUAL/development/importing-modules.section.md" \
    "$MANUAL/development/replace-modules.section.md" \
    "$MANUAL/development/freeform-modules.section.md" \
    "$MANUAL/development/settings-options.section.md" \
    "$MANUAL/development/meta-attributes.section.md" \
    "$MANUAL/development/assertions.section.md"

merge_pages "nixos-testing.md" "NixOS Tests" \
    "https://nixos.org/manual/nixos/stable/#sec-nixos-tests" "NixOS/nixpkgs" \
    "$MANUAL/development/nixos-tests.chapter.md" \
    "$MANUAL/development/writing-nixos-tests.section.md" \
    "$MANUAL/development/running-nixos-tests.section.md" \
    "$MANUAL/development/running-nixos-tests-interactively.section.md"

merge_pages "nixos-profiles.md" "NixOS Configuration Profiles" \
    "https://nixos.org/manual/nixos/stable/#ch-profiles" "NixOS/nixpkgs" \
    "$MANUAL/configuration/profiles.chapter.md" \
    "$MANUAL/configuration/profiles/minimal.section.md" \
    "$MANUAL/configuration/profiles/base.section.md" \
    "$MANUAL/configuration/profiles/headless.section.md" \
    "$MANUAL/configuration/profiles/graphical.section.md" \
    "$MANUAL/configuration/profiles/demo.section.md" \
    "$MANUAL/configuration/profiles/all-hardware.section.md" \
    "$MANUAL/configuration/profiles/docker-container.section.md" \
    "$MANUAL/configuration/profiles/clone-config.section.md" \
    "$MANUAL/configuration/profiles/installation-device.section.md" \
    "$MANUAL/configuration/profiles/qemu-guest.section.md" \
    "$MANUAL/configuration/profiles/perlless.section.md"

merge_pages "nixos-building-images.md" "Building NixOS Images" \
    "https://nixos.org/manual/nixos/stable/#sec-building-image" "NixOS/nixpkgs" \
    "$MANUAL/installation/building-nixos.chapter.md" \
    "$MANUAL/installation/building-images-via-nixos-rebuild-build-image.chapter.md" \
    "$MANUAL/installation/building-images-via-systemd-repart.chapter.md"

# ── Nix Pills ─────────────────────────────────────────────────────────

echo ""
echo "--- Nix Pills ---"

merge_pages "nix-pills.md" "Nix Pills - A Progressive Learning Series" \
    "https://nixos.org/guides/nix-pills/" "NixOS/nix-pills" \
    "$PILLS/00-preface.md" \
    "$PILLS/01-why-you-should-give-it-a-try.md" \
    "$PILLS/02-install-on-your-running-system.md" \
    "$PILLS/03-enter-environment.md" \
    "$PILLS/04-basics-of-language.md" \
    "$PILLS/05-functions-and-imports.md" \
    "$PILLS/06-our-first-derivation.md" \
    "$PILLS/07-working-derivation.md" \
    "$PILLS/08-generic-builders.md" \
    "$PILLS/09-automatic-runtime-dependencies.md" \
    "$PILLS/10-developing-with-nix-shell.md" \
    "$PILLS/11-garbage-collector.md" \
    "$PILLS/12-inputs-design-pattern.md" \
    "$PILLS/13-callpackage-design-pattern.md" \
    "$PILLS/14-override-design-pattern.md" \
    "$PILLS/15-nix-search-paths.md" \
    "$PILLS/16-nixpkgs-parameters.md" \
    "$PILLS/17-nixpkgs-overriding-packages.md" \
    "$PILLS/18-nix-store-paths.md" \
    "$PILLS/19-fundamentals-of-stdenv.md" \
    "$PILLS/20-basic-dependencies-and-hooks.md"

# ── Release Wiki ───────────────────────────────────────────────────────

echo ""
echo "--- Release Wiki ---"

merge_pages "release-process.md" "NixOS Release Process" \
    "https://nixos.github.io/release-wiki/" "NixOS/release-wiki" \
    "$RELEASE/Home.md" \
    "$RELEASE/Roles.md" \
    "$RELEASE/Release-Managers.md" \
    "$RELEASE/Release-Editors.md" \
    "$RELEASE/Release-Critical-Packages.md" \
    "$RELEASE/Release-Process.md" \
    "$RELEASE/Once-Appointed.md" \
    "$RELEASE/Feature-Freeze-Announcement.md" \
    "$RELEASE/Zero-Hydra-Failures.md" \
    "$RELEASE/Staging-Branch-Off.md" \
    "$RELEASE/Branch-Off.md" \
    "$RELEASE/Beta-Phase.md" \
    "$RELEASE/Final-Release.md" \
    "$RELEASE/Retrospective.md" \
    "$RELEASE/EOL-Cleanup.md" \
    "$RELEASE/Handover.md"

# ── Write version metadata ────────────────────────────────────────────

echo ""
echo "==> Writing metadata..."

cat > "$REFS_DIR/.wiki-version" <<EOF
nixdev_commit='$NIXDEV_COMMIT'
nixdev_date='$NIXDEV_DATE'
nixpkgs_commit='$NIXPKGS_COMMIT'
nixpkgs_date='$NIXPKGS_DATE'
pills_commit='$PILLS_COMMIT'
pills_date='$PILLS_DATE'
release_commit='$RELEASE_COMMIT'
release_date='$RELEASE_DATE'
EOF

TOTAL=$(find "$REFS_DIR" -name '*.md' | wc -l)
echo "==> Done! Generated $TOTAL reference files."
echo "    Output: $REFS_DIR/"

if [[ $MISSING_SOURCES -gt 0 ]]; then
    echo "ERROR: $MISSING_SOURCES source file(s) missing upstream (renamed or removed)." >&2
    echo "Update the paths in this script, otherwise the affected references go stale." >&2
    exit 1
fi
