mode = "dark"

accent = "#8be9fd"
selection = "#44475a"
muted = "#44475a"

background = "#282a36"
dark_background = "#1e2029"
darker_background = "#14151b"
lighter_background = "#44475a"

foreground = "#f8f8f2"
dark_foreground = "#a0a19f"
light_foreground = "#fbfbf6"
bright_foreground = "#ffffff"

red = "#ffafcc"
yellow = "#cbc3e3"
orange = "#ffb86c"
green = "#8be9fd"
cyan = "#8be9fd"
blue = "#8be9fd"
magenta = "#ffc8dd"
brown = "#755f69"

bright_red = "#ffafcc"
bright_yellow = "#cbc3e3"
bright_green = "#bde0fe"
bright_cyan = "#bde0fe"
bright_blue = "#bde0fe"
bright_magenta = "#ffc8dd"

hyprland_active_border = "rgba(F8F8F2ee) rgba(8BE9FDee) 45deg"
hyprland_inactive_border = "rgba(282A3688)"
