#!/bin/bash
# Shared generator for the clip designs (Storm, Eyes, Rally, River): the
# clip's first frame is the boot screen and the rest of it plays as a frame
# sequence when the passphrase checks out, the same deal as the QML
# ClipDesign. Frames are preloaded by the theme script because switch_root
# wipes the initramfs from RAM right after the unlock.
#
# Usage (from a design's generate.sh): cliptwin.sh <staging> <design-id> <clip-file>
set -euo pipefail
source "$(dirname "$(realpath "$0")")/common.sh"

staging="${1:?usage: cliptwin.sh <staging-dir> <design-id> <clip-file>}"
design="${2:?missing design id}"
clip="$HOME/.config/omarchy/lock-videos/${3:?missing clip filename}"

if [[ ! -f $clip ]]; then
  echo "Missing $clip - drop the design's video in ~/.config/omarchy/lock-videos first" >&2
  exit 1
fi

mkdir -p "$staging"

bg=$(theme_color background)
fg=$(theme_color foreground)
dim=$(mix_hex 888888 ffffff 0.3)
family=$(mono_font_family)

fg_f=$(hex_floats "$fg"); dim_f=$(hex_floats "$dim"); bg_i=$(hex_ints "$bg"); fg_i=$(hex_ints "$fg")

# Render frames at the panel's native resolution when we can see it.
res=$(hyprctl monitors -j 2>/dev/null | python3 -c "
import json, sys
try:
    m = json.load(sys.stdin)[0]
    print(m['width'], m['height'])
except Exception:
    print('1920 1080')
" 2>/dev/null || echo "1920 1080")
w=${res%% *}; h=${res##* }

# Preview mode stops after the thumbnail: one frame instead of the whole
# sequence, so the explorer can render its cards quickly.
if [[ ${PREVIEW_ONLY:-0} == 1 ]]; then
  ffmpeg -v error -y -i "$clip" -vf "scale=720:405:force_original_aspect_ratio=increase,crop=720:405" -frames:v 1 "$staging/first.png"
  magick -size 220x30 xc:none -draw "fill rgba($bg_i,0.55) roundrectangle 0,0 219,29 15,15" "$staging/pill-s.png"
  magick "$staging/first.png" \
    \( -size 720x101 gradient:'#00000073-#00000000' \) -geometry +0+0 -composite \
    \( -size 720x121 gradient:'#00000000-#00000080' \) -geometry +0+284 -composite \
    "$staging/pill-s.png" -gravity south -geometry +0+18 -composite \
    "$staging/preview.png"
  exit 0
fi

# Whole clip by default, capped at 72 frames: drop the frame rate for longer
# clips rather than cutting them short. BOOT_CLIP_SECONDS trims the clip to
# the first N seconds instead (0 or unset plays it all).
duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$clip")
limit="${BOOT_CLIP_SECONDS:-0}"
if awk -v l="$limit" -v d="$duration" 'BEGIN { exit !(l > 0 && l < d) }'; then
  duration=$limit
fi
fps=$(awk -v d="$duration" 'BEGIN { f = 72 / d; if (f > 12) f = 12; printf "%.3f", f }')

ffmpeg -v error -y -t "$duration" -i "$clip" -vf "fps=$fps,scale=$w:$h:force_original_aspect_ratio=increase,crop=$w:$h" \
  -start_number 0 "$staging/fr%02d.png"
num_frames=$(ls "$staging"/fr*.png | wc -l)

# The still: first frame with the ClipDesign scrims baked in.
magick "$staging/fr00.png" \
  \( -size "${w}x$((h / 4))" gradient:'#00000073-#00000000' \) -geometry +0+0 -composite \
  \( -size "${w}x$((h * 3 / 10))" gradient:'#00000000-#00000080' \) -geometry "+0+$((h - h * 3 / 10))" -composite \
  "$staging/still.png"

magick -size 400x56 xc:none -draw "fill rgba($bg_i,0.55) roundrectangle 0,0 399,55 28,28" "$staging/pill.png"
magick -size 14x14 xc:none -fill "rgba($fg_i,0.95)" -draw "circle 7,7 7,2" "$staging/dot.png"

write_theme_ini "$staging" "$bg" "$family"
echo "$design" > "$staging/design"

# Thumbnail for the explorer's boot panel: the still with the pill on it.
magick "$staging/still.png" -resize 720x405^ -gravity center -extent 720x405 \
  \( "$staging/pill.png" -resize x34 \) -gravity south -geometry +0+30 -composite \
  "$staging/preview.png"

cat > "$staging/omarchy-boot.script" <<EOF
# Clip design twin ($design), generated by omarchy-lock-explorer.
# First frame is the lock, the rest plays when you unlock.

fg.r = ${fg_f%%,*}; fg.g = $(echo "$fg_f" | cut -d, -f2); fg.b = $(echo "$fg_f" | cut -d, -f3);
dim.r = ${dim_f%%,*}; dim.g = $(echo "$dim_f" | cut -d, -f2); dim.b = $(echo "$dim_f" | cut -d, -f3);

font.body = "$family 15";
font.small = "$family 12";

clip.fps = $fps;
num_frames = $num_frames;

Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

screen.w = Window.GetWidth();
screen.h = Window.GetHeight();

digits = "0123456789";

fun frame_name(i) {
  d1 = Math.Int(i / 10);
  return "fr" + digits.CharAt(d1) + digits.CharAt(i - d1 * 10) + ".png";
}

still.image = Image("still.png");
if (still.image.GetWidth() != screen.w) still.image = still.image.Scale(screen.w, screen.h);
still.sprite = Sprite(still.image);
still.sprite.SetPosition(0, 0, 1);

# The clip only ever plays after a passphrase prompt on the way up; during
# reboot/shutdown plymouthd runs this theme too, and decoding the whole
# sequence there would waste the shutdown on frames never shown.
$(emit_downward_gate boot_like)

if (global.boot_like == 1) {
  for (i = 0; i < num_frames; i++) {
    frames[i] = Image(frame_name(i));
    if (frames[i].GetWidth() != screen.w) frames[i] = frames[i].Scale(screen.w, screen.h);
  }
}

#----------------------------------------- Chrome --------------------------------

pill.image = Image("pill.png");
pill.sprite = Sprite(pill.image);
pill.x = screen.w / 2 - pill.image.GetWidth() / 2;
pill.y = screen.h * 0.93 - 10 - pill.image.GetHeight();
pill.sprite.SetPosition(pill.x, pill.y, 10);

placeholder.image = Image.Text("Password", dim.r, dim.g, dim.b, 1, font.body);
placeholder.sprite = Sprite(placeholder.image);
placeholder.x = pill.x + 24;
placeholder.y = pill.y + pill.image.GetHeight() / 2 - placeholder.image.GetHeight() / 2;
placeholder.sprite.SetPosition(placeholder.x, placeholder.y, 11);

bullet.image = Image("dot.png");
for (i = 0; i < 24; i++) {
  bullets[i] = Sprite();
  bullets[i].SetOpacity(0);
}

fun hide_bullets() {
  for (i = 0; i < 24; i++) bullets[i].SetOpacity(0);
}

global.password_shown = 0;
global.playing = 0;
global.tick = 0;
global.cur_frame = -1;

fun set_chrome_opacity(op) {
  pill.sprite.SetOpacity(op);
  placeholder.sprite.SetOpacity(op);
  if (op == 0) hide_bullets();
}

# Hidden until a passphrase prompt actually fires: plymouthd runs this theme
# for reboot/shutdown too (and for unencrypted boots), where a visible entry
# reads as a prompt that will never accept input.
set_chrome_opacity(0);

fun display_password_callback(prompt_text, count) {
  global.password_shown = 1;

  if (global.playing == 1) {
    # The clip starts on submit, not on success: a prompt firing again means
    # the passphrase was wrong. Rewind to the still and bring the entry back.
    global.playing = 0;
    global.tick = 0;
    global.cur_frame = -1;
    still.sprite.SetImage(still.image);
  }
  set_chrome_opacity(1);

  if (count > 24) count = 24;

  step = bullet.image.GetWidth() + 8;
  cy = pill.y + pill.image.GetHeight() / 2;
  for (i = 0; i < 24; i++) {
    if (i < count) {
      bullets[i].SetImage(bullet.image);
      bullets[i].SetPosition(placeholder.x + i * step, cy - bullet.image.GetHeight() / 2, 11);
      bullets[i].SetOpacity(1);
    } else {
      bullets[i].SetOpacity(0);
    }
  }
  if (count > 0) placeholder.sprite.SetOpacity(0);
  else placeholder.sprite.SetOpacity(1);
}

fun display_normal_callback() {
  if (global.password_shown == 1 && global.playing == 0) {
    # Outside boot the frames were never loaded, so a submitted answer just
    # drops the chrome and keeps the still.
    if (global.boot_like == 1) {
      global.playing = 1;
      global.tick = 0;
    }
    set_chrome_opacity(0);
  }
}

fun refresh_callback() {
  if (global.playing == 1) {
    global.tick++;
    f = Math.Int(global.tick * clip.fps / 50);
    if (f >= num_frames) f = num_frames - 1;
    if (f != global.cur_frame) {
      global.cur_frame = f;
      still.sprite.SetImage(frames[f]);
    }
  }
}

message_sprite = Sprite();
message_sprite.SetPosition(20, screen.h - 30, 12);

fun display_message_callback(text) {
  message_sprite.SetImage(Image.Text(text, dim.r, dim.g, dim.b, 1, font.small));
  message_sprite.SetOpacity(1);
}

fun hide_message_callback(text) {
  message_sprite.SetOpacity(0);
}

Plymouth.SetDisplayPasswordFunction(display_password_callback);
Plymouth.SetDisplayNormalFunction(display_normal_callback);
Plymouth.SetRefreshFunction(refresh_callback);
Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);
EOF
