# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282a36"

# Main text color
theme[main_fg]="#f8f8f2"

# Title color for boxes
theme[title]="#f8f8f2"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8be9fd"

# Background color of selected item in processes box
theme[selected_bg]="#44475a"

# Foreground color of selected item in processes box
theme[selected_fg]="#f8f8f2"

# Color of inactive/disabled text
theme[inactive_fg]="#44475a"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#f8f8f2"

# Background color of the percentage meters
theme[meter_bg]="#44475a"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bd93f9"

# Cpu box outline color
theme[cpu_box]="#bd93f9"

# Memory/disks box outline color
theme[mem_box]="#50fa7b"

# Net up/down box outline color
theme[net_box]="#bd93f9"

# Processes box outline color
theme[proc_box]="#ff79c6"

# Box divider line and small boxes line color
theme[div_line]="#44475a"

# Temperature graph colors
theme[temp_start]="#8be9fd"
theme[temp_mid]="#ffb86c"
theme[temp_end]="#ff5555"

# CPU graph colors
theme[cpu_start]="#bd93f9"
theme[cpu_mid]="#8be9fd"
theme[cpu_end]="#50fa7b"

# Mem/Disk free meter
theme[free_start]="#6272a4"
theme[free_mid]="#50fa7b"
theme[free_end]="#69ff94"

# Mem/Disk cached meter
theme[cached_start]="#6272a4"
theme[cached_mid]="#8be9fd"
theme[cached_end]="#a4ffff"

# Mem/Disk available meter
theme[available_start]="#bd93f9"
theme[available_mid]="#ffb86c"
theme[available_end]="#f1fa8c"

# Mem/Disk used meter
theme[used_start]="#96faaf"
theme[used_mid]="#50fa7b"
theme[used_end]="#0dfa49"

# Download graph colors
theme[download_start]="#bd93f9"
theme[download_mid]="#50fa7b"
theme[download_end]="#8be9fd"

# Upload graph colors
theme[upload_start]="#bd93f9"
theme[upload_mid]="#ff79c6"
theme[upload_end]="#ff92df"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#50fa7b"
theme[process_mid]="#59b690"
theme[process_end]="#6272a4"
