#!/bin/bash
# The lock screen half of a unified custom layout: reads the same layout.conf
# the boot screen uses and emits a matching Quickshell lock design QML into
# ~/.config/omarchy/lock-designs/, plus a preview PNG for the editor. So one
# layout gives you a lock screen and a boot screen that look the same.
#
# Usage: genlock.sh <layout.conf> <name> [preview-out.png]
set -euo pipefail
source "$(dirname "$(realpath "$0")")/../common.sh"

conf="${1:?usage: genlock.sh <layout.conf> <name> [preview-out.png]}"
name="${2:?missing name}"
preview_out="${3:-}"
[[ -f $conf ]] || { echo "No such layout: $conf" >&2; exit 1; }

conf_get() {
  awk -F= -v k="$1" '
    /^[ \t]*#/ { next }
    { key=$1; gsub(/^[ \t]+|[ \t]+$/,"",key)
      if (key==k) { sub(/^[^=]*=/,""); gsub(/^[ \t]+|[ \t]+$/,""); print; exit } }' "$conf"
}
val() { local v; v=$(conf_get "$1"); printf '%s' "${v:-$2}"; }

background=$(val background theme)
logo=$(val logo none)
title=$(val title "")
title_y=$(val title_y 18)
subtitle=$(val subtitle "")
clock=$(val clock on)
entry=$(val entry pill)
entry_y=$(val entry_y 72)

qml_color() { # role -> a Color/withAlpha expression for lock QML
  case "$1" in
    foreground) echo "Color.lock.text" ;;
    accent)     echo "Color.lock.borderActive" ;;
    dim)        echo 'lock.withAlpha(Color.lock.text, 0.6)' ;;
    background) echo "Color.background" ;;
    '#'*)       echo "\"$1\"" ;;
    *)          echo "Color.lock.text" ;;
  esac
}
title_c=$(qml_color "$(val title_color foreground)")
subtitle_c=$(qml_color "$(val subtitle_color dim)")

expand_vars() { local s=${1//'$USER'/$USER}; printf '%s' "${s//'$HOST'/$(hostname)}"; }
esc_qml() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
title_q=$(esc_qml "$(expand_vars "$title")"); subtitle_q=$(esc_qml "$(expand_vars "$subtitle")")

# ------------------------------------------------ background block
case "$background" in
  theme)      bg_block='Rectangle { anchors.fill: parent; color: Color.background }' ;;
  wallpaper)  bg_block='Wallpaper { anchors.fill: parent; lock: lock; blur: 0.9; dim: 0.25 }' ;;
  '#'*)       bg_block="Rectangle { anchors.fill: parent; color: \"$background\" }" ;;
  *)          bg_block='Wallpaper { anchors.fill: parent; lock: lock; blur: 0.9; dim: 0.25 }' ;;
esac

# ------------------------------------------------ QML
out_dir="$HOME/.config/omarchy/lock-designs"
mkdir -p "$out_dir"
qml="$out_dir/$name.qml"

{
cat <<EOF
import QtQuick
import qs.Commons
import "../plugins/io.github.sirjul1337.lock-explorer/designs"

// Generated by omarchy-lock-explorer from a custom layout ($name). Its boot
// screen twin comes from the same layout.conf.
DesignBase {
  id: lock
  inputItem: field.input

  $bg_block

  MouseArea {
    anchors.fill: parent
    hoverEnabled: true
    onClicked: { lock.wakeRequested(); lock.forcePasswordFocus() }
    onPositionChanged: lock.wakeRequested()
  }
EOF

if [[ $clock == on ]]; then
cat <<EOF

  Column {
    anchors.horizontalCenter: parent.horizontalCenter
    anchors.top: parent.top
    anchors.topMargin: Math.round(lock.height * ${title_y} / 100)
    spacing: 4
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: Qt.formatTime(lock.now, "HH:mm")
      color: Color.lock.text
      font.family: Style.font.family
      font.pixelSize: Math.round(Style.font.baseSize * 7)
      font.weight: Font.Light
    }
EOF
[[ -n $title ]] && cat <<EOF
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: "$title_q"
      color: $title_c
      font.family: Style.font.family
      font.pixelSize: Style.font.display
    }
EOF
[[ -n $subtitle ]] && cat <<EOF
    Text {
      anchors.horizontalCenter: parent.horizontalCenter
      text: "$subtitle_q"
      color: $subtitle_c
      font.family: Style.font.family
      font.pixelSize: Style.font.bodySmall
    }
EOF
echo "  }"
else
[[ -n $title ]] && cat <<EOF

  Text {
    anchors.horizontalCenter: parent.horizontalCenter
    anchors.top: parent.top
    anchors.topMargin: Math.round(lock.height * ${title_y} / 100)
    text: "$title_q"
    color: $title_c
    font.family: Style.font.family
    font.pixelSize: Style.font.heading
  }
EOF
fi

if [[ $entry != none ]]; then
cat <<EOF

  PasswordField {
    id: field
    lock: lock
    anchors.horizontalCenter: parent.horizontalCenter
    y: Math.round(lock.height * ${entry_y} / 100) - height / 2
    width: 400
    height: 54
    radius: $([[ $entry == line ]] && echo 0 || echo 27)
    placeholder: "Password"
  }
EOF
else
cat <<'EOF'

  LockInput { id: field; lock: lock; width: 1; height: 1; opacity: 0 }
EOF
fi

echo "}"
} > "$qml"

echo "$qml"

# ------------------------------------------------ preview PNG (720x405)
[[ -z $preview_out ]] && exit 0

bg_t=$(theme_color background); fg_t=$(theme_color foreground)
family=$(mono_font_family); font_file=$(fc-match -f '%{file}' "$family")
tc=$(theme_color foreground)
pv=( -size 720x405 "xc:#$bg_t" )
if [[ $background == wallpaper || ( $background != theme && $background != '#'* ) ]]; then
  link="$HOME/.local/state/omarchy/current/background"
  [[ -e $link ]] && pv=( "$(readlink -f "$link")" -resize '720x405^' -gravity center -extent 720x405 -blur 0x10 -fill black -colorize 22 )
elif [[ $background == '#'* ]]; then
  pv=( -size 720x405 "xc:$background" )
fi
args=( magick "${pv[@]}" -font "$font_file" -gravity north )
if [[ $clock == on ]]; then
  cy=$(awk -v y="$title_y" 'BEGIN{printf "%d", 405*y/100}')
  args+=( -pointsize 54 -fill "#$fg_t" -annotate +0+$cy "09:41" )
  [[ -n $title ]] && args+=( -pointsize 16 -fill "#$fg_t" -annotate +0+$((cy + 66)) "$title" )
elif [[ -n $title ]]; then
  cy=$(awk -v y="$title_y" 'BEGIN{printf "%d", 405*y/100}')
  args+=( -pointsize 22 -fill "#$fg_t" -annotate +0+$cy "$title" )
fi
if [[ $entry != none ]]; then
  ey=$(awk -v y="$entry_y" 'BEGIN{printf "%d", 405*y/100 - 12}')
  bg_i=$(hex_ints "$bg_t")
  args+=( \( -size 190x24 xc:none -draw "fill rgba($bg_i,0.55) roundrectangle 0,0 189,23 $([[ $entry == line ]] && echo 0 || echo 12),$([[ $entry == line ]] && echo 0 || echo 12)" \) -geometry +0+$ey -composite )
fi
args+=( "$preview_out" )
"${args[@]}"
